### ISSUE TITLE
Looks like the transform is not up on dockerhub?

### ISSUE THREAD

**Issue by prismofeverything** [biostream/gdsc-transform#3]
Getting this error when running the gdsc-transform:

```Unable to find image 'biostream/gdsc-transform:latest' locally
Pulling repository docker.io/biostream/gdsc-transform
docker: Error: image biostream/gdsc-transform:latest not found.
See 'docker run --help'.```

**Comment by prismofeverything** [comment]
This happened again (as I suppose it would). How do we trigger the build of these images?

**Comment by adamstruck** [comment]
In this case there wasn't even a dockerhub entry for this image. I created one and triggered the build manually.

**Comment by adamstruck** [comment]
Looks like the build failed. https://hub.docker.com/r/biostream/gdsc-transform/builds/bhnrrvpd4rsdtn2zmmqfltg/

**Comment by prismofeverything** [comment]
Is there a reason we are installing python and pandas from scratch rather than using some python image as a starting point?

I mean, the apt command should work, but that maybe we can simplify the process/failure modes for docker.
